### PR TITLE
Adding Updated README

### PR DESCRIPTION
**Pull request by Jailander**
@marc-hanheide I am very curious about what is going on, why does github keep aggragating all my commits everytime I make a PR

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Because you make them all from the same branch which you hadn't synced with master??

**Comment by Jailander** [comment]
yes I Pull from master, look at my last commit (and there are a few like this)

**Comment by cdondrup** [comment]
I has the same just an hour ago. I added commit to the branch which was last merged into the master and it wanted to make that commit again when I created the PR. Maybe a new "feature"?

I just create a new branch for every change now.

**Comment by Jailander** [comment]
yes its been happening to me since yesterday must be a "feature" then, will follow @cdondrup 's approach as usual :D

**Pull request merged**
